services:
  fastapi:
    build: .
    image: fastapi
    container_name: fastapi
    restart: always
    command: "python src/main.py"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - "postgres:dbps"
      - "postgres_test:dbps_test"
    depends_on:
      - postgres
      - postgres_test
    networks:
      - dbnet
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    env_file: "dev.env"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dbnet
  postgres_test:
    image: postgres:17-alpine
    container_name: postgres_test
    env_file: "test.env"
    volumes:
      - postgres-data-test:/var/lib/postgresql/data
    networks:
      - dbnet
  adminer:
    image: adminer:standalone
    container_name: adminer
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - "postgres_test:db_test"
      - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres
      - postgres_test
      
networks:
  dbnet:
    driver: bridge
volumes:
  postgres-data:
  postgres-data-test: