services:
  fastapi:
    build: .
    image: fastapi
    container_name: fastapi
    restart: always
    command: "python src/main.py"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    links:
      - "postgres:dbps"
    depends_on:
      - postgres
    networks:
      - dbnet
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - dbnet
  adminer:
    image: adminer:standalone
    container_name: adminer
    ports:
      - "127.0.0.1:8080:8080"
    links:
      - "postgres:db"
    networks:
      - dbnet
    depends_on:
      - postgres
networks:
  dbnet:
    driver: bridge
volumes:
  postgres-data: