"""empty message

Revision ID: f74475c21183
Revises: 4aa5f2c1c5b7
Create Date: 2025-09-18 17:09:35.718594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f74475c21183'
down_revision: Union[str, None] = '4aa5f2c1c5b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('created_at_db', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    op.add_column('workers', sa.Column('updated_at_db', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'updated_at_db')
    op.drop_column('workers', 'created_at_db')
    # ### end Alembic commands ###
